# Generated by Django 5.0.3 on 2024-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
