# Generated by Django 5.0.3 on 2024-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_activ_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
