# Generated by Django 5.0.3 on 2024-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
