# Generated by Django 5.0.3 on 2024-04-26 22:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_images_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='post_images'),
        ),
    ]
