# Generated by Django 5.0.3 on 2024-04-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_account_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('Ai', 'Ai'), ('programming', 'programming'), ('blockchain', 'blockchain')], default='Ai', max_length=20),
        ),
    ]
