# Generated by Django 5.0.3 on 2024-05-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_image_remove_images_post_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reading_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('قائم30', 'قائم30'), ('کاویان', 'کاویان'), ('سنگ شور', 'سنگ شور'), ('نبرد', 'نبرد'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
