# Generated by Django 5.0.3 on 2024-05-13 00:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_reading_time_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[1920, 1080], upload_to='account_images/', verbose_name='تصویر'),
        ),
    ]
