# Generated by Django 5.0.3 on 2024-05-13 00:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='post_images/'),
        ),
    ]
