# Generated by Django 5.0.3 on 2024-05-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('قائم30', 'قائم30'), ('کاویان', 'کاویان'), ('سنگ شور', 'سنگ شور'), ('نورد  ', 'نورد'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
